# Generated by Django 2.2.24 on 2021-09-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fotografia',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
