# Generated by Django 2.2.24 on 2021-09-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20210911_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fotografia',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
