# Generated by Django 2.2.24 on 2021-09-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20210911_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
